apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 8
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: shivakumar09/hire-app:30
        ports:
        - containerPort: 8080
